name: crm_client
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_svg:
  get_it:
  provider:
  intl:
  mocktail:
  dio:
  flutter_secure_storage:

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/assets/app_logo.png"
  min_sdk_android: 21

flutter:

  uses-material-design: true

  assets:
    - lib/assets/svg/app_logo.svg
    - lib/assets/svg/swiper.svg
    - lib/assets/svg/qr.svg

  fonts:
    - family: MontserratAlternates
      fonts:
        - asset: lib/assets/fonts/MontserratAlternates.ttf
